# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostMessage',
        ),
    ]
